### ISSUE TITLE
Embedly API Key Security

### ISSUE THREAD

**Issue by LandonSchropp** [embedly/embedly-jquery#54]
In the readme, it suggests setting the Embedly key like this:

> `$('#content a').embedly({key: 'Your Embedly Key'});`

Maybe I'm missing something obvious here, but if I set my Embedly API key in my client-side JavaScript, what's to stop somebody else from stealing it? Couldn't somebody easily do the following?

1. Write a script to crawl websites and look for `jquery.embedly.min.js`.
2. Download all of the JavaScripts associated with those sites.
3. Match `/embedly\([^)]*key:\s*['"]([^'"]+)['"]/`
4. Grab those keys and go to town.

**Comment by screeley** [comment]
Hi Landon,

If this is a concern for you, the best option is to use a backend proxy that will shield your key. 

In practice, this is is not an issue. We have never seen an instance of someone going to town on another person's key. Embedly's service is free at base levels.

If you have further concerns, please reach out to support@embed.ly as this is more of a general case issue rather than an Embedly jQuery issue. 

Best,

Sean
